name: Build and Deploy
on: [push, workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Release
      run: |
          latestZipUrl=$(curl https://api.github.com/repos/videotogether/videotogether/releases/latest -s | jq -r '.zipball_url')
          wget $latestZipUrl -O latest.zip
          unzip latest.zip -d /tmp/latest
          mkdir -p ./tmp
          cp -r /tmp/latest/*/release ./tmp
          ls ./tmp && ls -a

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: VideoTogether/VideoTogether.github.io
        TARGET_BRANCH: main
        BUILD_SCRIPT: yarn && yarn build && cp -r ./tmp/release/ ./.vitepress/dist/ && rm -rf tmp
        BUILD_DIR: ./.vitepress/dist
